### ISSUE TITLE
Some features

### ISSUE THREAD

**Issue by yuler** [yuler/gh-todo#3]
- [x] More detail in README, why create three TODO daily?
- [x] Add template for `gh todo init` command
- [x] Add some CI in template
- [ ] #9
- [ ] #6
- [ ] #4
- [ ] #8

**Comment by maigl** [comment]
It would also be awesome to be able to mark a todo item as done.

**Comment by yuler** [comment]
> It would also be awesome to be able to mark a todo item as done.

Good idea, do you have any suggestions about interaction?

```bash
gh todo done <number>
```

Like it? Or more interactive?

**Comment by yuler** [comment]
Splitting task list to issues
